// Loads the precomputed embedding index. The JSON is generated by
// `npm run ingest` and bundled at build time via a static import, so it works
// on serverless without filesystem access. Until ingestion is run the file is
// an empty array, and retrieval degrades gracefully (no augmentation).
import raw from '@/data/knowledge/embeddings.json'

export interface EmbeddingRecord {
  id: string
  embedding: number[]
}

export function loadEmbeddingIndex(): EmbeddingRecord[] {
  return Array.isArray(raw) ? (raw as EmbeddingRecord[]) : []
}
