import { useState, useEffect } from 'react'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import {
  AlertTriangle, Phone, Lightbulb, CheckCircle2, ArrowRight,
  Pill, Leaf, ShieldAlert, Clock, Calendar, Activity,
  FileText, Copy, Check, TrendingUp, Printer, Users,
} from 'lucide-react'
import SymptomChat from '../components/SymptomChat'
import AppShell from '@/components/AppShell'
import { useLanguage } from '@/lib/i18n/LanguageContext'

interface Condition {
  name: string
  probability: number
  reasoning: string
}

interface Medicine {
  name: string
  type: 'OTC' | 'PRESCRIPTION' | 'ADVICE'
  purpose: string
  dosage: string
  warning?: string
}

interface Assessment {
  symptoms: string[]
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
  possibleConditions: (Condition | string)[]
  medicineSuggestions?: Medicine[]
  nonMedicineApproaches?: string[]
  redFlags?: string[]
  recoveryTimeline?: string
  recommendation: string
  recommendedSpecialist?: string
  advice: string
  completed: boolean
}

const barColors = ['bg-sky-500', 'bg-violet-500', 'bg-amber-400', 'bg-emerald-500']

export default function SymptomCheck() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const { t } = useLanguage()

  const severityConfig = {
    LOW:      { label: t('symptom.severityLow'),      headerBg: 'bg-emerald-600', badgeBg: 'bg-emerald-100 text-emerald-700' },
    MEDIUM:   { label: t('symptom.severityMedium'),   headerBg: 'bg-amber-500',   badgeBg: 'bg-amber-100 text-amber-700' },
    HIGH:     { label: t('symptom.severityHigh'),     headerBg: 'bg-orange-600',  badgeBg: 'bg-orange-100 text-orange-700' },
    CRITICAL: { label: t('symptom.severityCritical'), headerBg: 'bg-red-600',     badgeBg: 'bg-red-100 text-red-700' },
  }

  const tips = [
    t('symptom.tip1'), t('symptom.tip2'), t('symptom.tip3'), t('symptom.tip4'), t('symptom.tip5'),
  ]

  const [assessment, setAssessment] = useState<Assessment | null>(null)
  const [symptomLogId, setSymptomLogId] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (status === 'unauthenticated') router.push('/api/auth/signin')
  }, [status, router])

  const handleAssessmentComplete = (a: Assessment, logId: string) => {
    setAssessment(a)
    setSymptomLogId(logId)
    setTimeout(() => {
      document.getElementById('assessment-panel')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }, 100)
  }

  const generateNoteText = () => {
    if (!assessment) return ''
    const date = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    const patientName = session?.user?.name || 'Patient'
    const topConditions = assessment.possibleConditions
      .slice(0, 3)
      .map(c => typeof c === 'string' ? `• ${c}` : `• ${c.name}${c.probability ? ` (${c.probability}%)` : ''}`)
      .join('\n')
    const medicines = (assessment.medicineSuggestions || [])
      .filter(m => m.type !== 'ADVICE')
      .slice(0, 3)
      .map(m => `• ${m.name}${m.dosage ? ` — ${m.dosage}` : ''} [${m.type}]`)
      .join('\n')
    const redFlags = (assessment.redFlags || []).map(f => `• ${f}`).join('\n')

    return `*HealthAI — Doctor Visit Note*
📅 Date: ${date}
👤 Patient: ${patientName}

*Chief Complaint:*
${assessment.symptoms.join(', ')}

*Severity:* ${assessment.severity}

*AI-Suggested Diagnosis:*
${topConditions || '—'}

*Suggested Medications:*
${medicines || '—'}

${redFlags ? `*⚠️ Red Flags — Seek care immediately if:*\n${redFlags}\n` : ''}
${assessment.recoveryTimeline ? `*Recovery Estimate:* ${assessment.recoveryTimeline}\n` : ''}
*AI Advice:*
${assessment.advice}

_Generated by HealthAI · For reference only — not a medical prescription_`
  }

  const handleCopyNote = async () => {
    const text = generateNoteText()
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = text
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    }
  }

  if (status === 'loading') {
    return (
      <AppShell title="Symptom Check">
        <div className="flex items-center justify-center h-64">
          <div className="flex items-center gap-3 text-slate-400">
            <div className="w-5 h-5 rounded-full border-2 border-sky-500/40 border-t-sky-500 animate-spin" />
            Loading…
          </div>
        </div>
      </AppShell>
    )
  }

  const sev = assessment ? (severityConfig[assessment.severity] ?? severityConfig.LOW) : null

  const conditions: Condition[] = assessment
    ? assessment.possibleConditions.map(c =>
        typeof c === 'string' ? { name: c, probability: 0, reasoning: '' } : c
      )
    : []

  const medicines = assessment?.medicineSuggestions || []
  const nonMed = assessment?.nonMedicineApproaches || []
  const redFlags = assessment?.redFlags || []

  return (
    <AppShell
      title={t('symptom.title')}
      breadcrumb={[{ label: t('nav.dashboard'), href: '/dashboard' }, { label: t('nav.symptomCheck') }]}
    >
      <div className="p-6 lg:p-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 max-w-7xl mx-auto">

          {/* ── Main column ── */}
          <div className="lg:col-span-2 flex flex-col gap-6">

            {/* Chat */}
            <div className="card flex flex-col" style={{ height: 560 }}>
              <div className="px-5 py-4 border-b border-slate-100 flex items-center gap-3 flex-shrink-0">
                <div className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
                <div>
                  <p className="text-sm font-semibold text-slate-900">{t('symptom.aiName')}</p>
                  <p className="text-xs text-slate-400">{t('symptom.aiPowered')}</p>
                </div>
                {assessment && (
                  <span className={`ml-auto text-xs font-semibold px-2.5 py-1 rounded-full ${sev?.badgeBg}`}>
                    {t('symptom.assessmentReady')}
                  </span>
                )}
              </div>
              <div className="flex-1 overflow-hidden">
                <SymptomChat onAssessmentComplete={handleAssessmentComplete} />
              </div>
            </div>

            {/* ── Assessment Panel ── */}
            {assessment && sev && (
              <div id="assessment-panel" className="rounded-2xl border border-slate-200 overflow-hidden shadow-sm">

                {/* Severity header */}
                <div className={`${sev.headerBg} px-6 py-4`}>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 bg-white/20 rounded-xl flex items-center justify-center">
                        <Activity size={18} className="text-white" />
                      </div>
                      <div>
                        <p className="text-white font-bold text-base">{t('symptom.assessmentTitle')}</p>
                        <p className="text-white/70 text-xs mt-0.5">{sev.label}</p>
                      </div>
                    </div>
                    <CheckCircle2 size={22} className="text-white/80" />
                  </div>
                </div>

                <div className="bg-white p-6 space-y-6">

                  {/* Advice + Symptoms row */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                    <div>
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">{t('symptom.reported')}</p>
                      <div className="flex flex-wrap gap-1.5">
                        {assessment.symptoms.map((s, i) => (
                          <span key={i} className="px-2.5 py-1 bg-slate-100 rounded-full text-xs font-medium text-slate-700">{s}</span>
                        ))}
                      </div>
                    </div>
                    <div>
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">{t('symptom.advice')}</p>
                      <p className="text-sm text-slate-700 leading-relaxed">{assessment.advice}</p>
                    </div>
                  </div>

                  {/* Conditions with probability bars */}
                  {conditions.length > 0 && (
                    <div>
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-3">{t('symptom.conditions')}</p>
                      <div className="space-y-4">
                        {conditions.map((c, i) => (
                          <div key={i}>
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-sm font-semibold text-slate-800">{c.name}</span>
                              {c.probability > 0 && (
                                <span className={`text-xs font-bold px-2 py-0.5 rounded-full text-white ${barColors[i % barColors.length]}`}>
                                  {c.probability}%
                                </span>
                              )}
                            </div>
                            {c.probability > 0 && (
                              <div className="h-2 bg-slate-100 rounded-full overflow-hidden mb-1">
                                <div className={`h-full rounded-full ${barColors[i % barColors.length]}`} style={{ width: `${c.probability}%` }} />
                              </div>
                            )}
                            {c.reasoning && <p className="text-xs text-slate-500">{c.reasoning}</p>}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Medicines + Non-medicine */}
                  {(medicines.length > 0 || nonMed.length > 0) && (
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                      {medicines.length > 0 && (
                        <div>
                          <div className="flex items-center gap-1.5 mb-3">
                            <Pill size={13} className="text-sky-600" />
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{t('symptom.medicines')}</p>
                          </div>
                          <div className="space-y-2">
                            {medicines.map((m, i) => (
                              <div key={i} className={`rounded-xl p-3 border ${
                                m.type === 'ADVICE' ? 'bg-amber-50 border-amber-100'
                                  : m.type === 'PRESCRIPTION' ? 'bg-violet-50 border-violet-100'
                                  : 'bg-sky-50 border-sky-100'
                              }`}>
                                <div className="flex items-start justify-between gap-2 mb-0.5">
                                  <p className="text-xs font-semibold text-slate-800 leading-snug">{m.name}</p>
                                  {m.type !== 'ADVICE' && (
                                    <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded-full flex-shrink-0 ${
                                      m.type === 'PRESCRIPTION' ? 'bg-violet-200 text-violet-700' : 'bg-sky-200 text-sky-700'
                                    }`}>{m.type}</span>
                                  )}
                                </div>
                                {m.purpose && <p className="text-[11px] text-slate-500">{m.purpose}</p>}
                                {m.dosage && <p className="text-[11px] font-medium text-slate-700 mt-0.5">{m.dosage}</p>}
                                {m.warning && (
                                  <p className="text-[11px] text-amber-700 mt-1 flex items-start gap-1">
                                    <AlertTriangle size={10} className="flex-shrink-0 mt-0.5" />{m.warning}
                                  </p>
                                )}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                      {nonMed.length > 0 && (
                        <div>
                          <div className="flex items-center gap-1.5 mb-3">
                            <Leaf size={13} className="text-emerald-600" />
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{t('symptom.natural')}</p>
                          </div>
                          <ul className="space-y-2">
                            {nonMed.map((tip, i) => (
                              <li key={i} className="flex items-start gap-2.5">
                                <div className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center flex-shrink-0 text-[10px] font-bold mt-px">{i + 1}</div>
                                <p className="text-xs text-slate-600 leading-relaxed">{tip}</p>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Red flags */}
                  {redFlags.length > 0 && (
                    <div className="bg-red-50 border border-red-100 rounded-2xl p-4">
                      <div className="flex items-center gap-2 mb-2.5">
                        <ShieldAlert size={15} className="text-red-600" />
                        <p className="text-xs font-bold text-red-700 uppercase tracking-wide">{t('symptom.redFlags')}</p>
                      </div>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
                        {redFlags.map((flag, i) => (
                          <div key={i} className="flex items-start gap-2">
                            <span className="text-red-400 mt-0.5 flex-shrink-0">•</span>
                            <p className="text-xs text-red-700">{flag}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Recovery + CTA */}
                  <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 pt-2 border-t border-slate-100">
                    {assessment.recoveryTimeline && (
                      <div className="flex items-center gap-2 flex-1">
                        <Clock size={14} className="text-slate-400 flex-shrink-0" />
                        <p className="text-xs text-slate-500">
                          <span className="font-semibold text-slate-700">{t('symptom.recovery')}: </span>
                          {assessment.recoveryTimeline}
                        </p>
                      </div>
                    )}
                    {(assessment.severity === 'MEDIUM' || assessment.severity === 'HIGH' || assessment.severity === 'CRITICAL') && (
                      <Link
                        href={`/appointments/new${symptomLogId ? `?symptomLogId=${symptomLogId}` : ''}`}
                        className="flex items-center gap-2 bg-sky-600 hover:bg-sky-700 text-white font-semibold text-sm px-5 py-2.5 rounded-xl transition-all whitespace-nowrap"
                      >
                        <Calendar size={14} />
                        {t('symptom.bookDoctor')}
                        <ArrowRight size={13} />
                      </Link>
                    )}
                    {assessment.recommendedSpecialist && (
                      <Link
                        href={`/find-doctors?specialization=${encodeURIComponent(assessment.recommendedSpecialist)}`}
                        className="flex items-center gap-2 bg-violet-600 hover:bg-violet-700 text-white font-semibold text-sm px-5 py-2.5 rounded-xl transition-all whitespace-nowrap"
                      >
                        <Users size={14} />
                        Find a {assessment.recommendedSpecialist}
                        <ArrowRight size={13} />
                      </Link>
                    )}
                  </div>
                </div>
              </div>
            )}

            {/* ── Doctor Visit Note ── */}
            {assessment && (
              <div className="rounded-2xl border border-slate-200 overflow-hidden shadow-sm">
                <div className="bg-slate-800 px-5 py-4 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-white/10 rounded-xl flex items-center justify-center flex-shrink-0">
                      <FileText size={15} className="text-white" />
                    </div>
                    <div>
                      <p className="text-white font-bold text-sm">{t('symptom.doctorNote')}</p>
                      <p className="text-slate-400 text-xs">{t('symptom.shareWhatsApp')}</p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={handleCopyNote}
                      className={`flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl transition-all ${
                        copied ? 'bg-emerald-500 text-white' : 'bg-white/10 hover:bg-white/20 text-white'
                      }`}
                    >
                      {copied ? <Check size={13} /> : <Copy size={13} />}
                      {copied ? t('common.copied') : t('common.copy')}
                    </button>
                    <button
                      onClick={() => window.print()}
                      className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-white transition-all"
                    >
                      <Printer size={13} />
                      {t('common.print')}
                    </button>
                  </div>
                </div>

                <div className="bg-slate-50 p-5">
                  <div className="bg-white rounded-xl border border-slate-100 p-5 font-mono text-xs text-slate-700 leading-relaxed space-y-3">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="font-bold text-slate-900 text-sm not-italic" style={{ fontFamily: 'inherit' }}>HealthAI — Doctor Visit Note</p>
                        <p className="text-slate-500 text-[11px] mt-0.5">
                          {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })} · Patient: {session?.user?.name || 'Patient'}
                        </p>
                      </div>
                      <span className={`text-[10px] font-bold px-2 py-1 rounded-lg ${sev?.badgeBg}`}>{assessment.severity}</span>
                    </div>

                    <div className="border-t border-dashed border-slate-200 pt-3 space-y-2.5">
                      <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">{t('symptom.chiefComplaint')}</p>
                        <p className="text-slate-800">{assessment.symptoms.join(', ')}</p>
                      </div>

                      {conditions.filter(c => c.probability > 0).length > 0 && (
                        <div>
                          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">{t('symptom.aiDiagnosis')}</p>
                          {conditions.slice(0, 3).map((c, i) => (
                            <p key={i} className="text-slate-700">
                              {i + 1}. {c.name}{c.probability ? ` — ${c.probability}% probability` : ''}
                            </p>
                          ))}
                        </div>
                      )}

                      {medicines.filter(m => m.type !== 'ADVICE').length > 0 && (
                        <div>
                          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">{t('symptom.suggestedMeds')}</p>
                          {medicines.filter(m => m.type !== 'ADVICE').slice(0, 3).map((m, i) => (
                            <p key={i} className="text-slate-700">• {m.name}{m.dosage ? ` — ${m.dosage}` : ''} <span className={`text-[9px] font-bold ${m.type === 'PRESCRIPTION' ? 'text-violet-600' : 'text-sky-600'}`}>[{m.type}]</span></p>
                          ))}
                        </div>
                      )}

                      {redFlags.length > 0 && (
                        <div>
                          <p className="text-[10px] font-bold text-red-400 uppercase tracking-widest mb-1">⚠ {t('symptom.redFlags')}</p>
                          {redFlags.slice(0, 3).map((f, i) => <p key={i} className="text-red-600">• {f}</p>)}
                        </div>
                      )}

                      {assessment.recoveryTimeline && (
                        <p className="text-slate-600"><span className="font-bold">Recovery:</span> {assessment.recoveryTimeline}</p>
                      )}
                    </div>

                    <p className="text-[10px] text-slate-400 border-t border-dashed border-slate-200 pt-2">
                      {t('symptom.disclaimer')}
                    </p>
                  </div>

                  <p className="text-xs text-slate-400 text-center mt-3 flex items-center justify-center gap-1.5">
                    <span className="text-emerald-500">✓</span>
                    {t('symptom.copyHint')}
                  </p>
                </div>
              </div>
            )}

            {/* ── Patterns teaser ── */}
            {assessment && (
              <Link
                href="/symptom-patterns"
                className="flex items-center justify-between bg-gradient-to-r from-violet-600 to-sky-600 rounded-2xl p-5 text-white group hover:opacity-95 transition-all shadow-sm"
              >
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center flex-shrink-0">
                    <TrendingUp size={18} className="text-white" />
                  </div>
                  <div>
                    <p className="font-bold text-sm">{t('symptom.viewPatterns')}</p>
                    <p className="text-white/70 text-xs mt-0.5">{t('symptom.patternsDesc')}</p>
                  </div>
                </div>
                <ArrowRight size={18} className="text-white/60 group-hover:text-white group-hover:translate-x-1 transition-all flex-shrink-0" />
              </Link>
            )}
          </div>

          {/* ── Sidebar ── */}
          <div className="flex flex-col gap-4">
            <div className="card border-red-100 bg-red-50 p-4">
              <div className="flex items-center gap-2 mb-3">
                <Phone size={16} className="text-red-600" />
                <p className="text-sm font-semibold text-red-900">{t('emergency.title')}</p>
              </div>
              <p className="text-xs text-red-700 mb-3 leading-relaxed">
                {t('emergency.desc')}
              </p>
              <a href="tel:112" className="btn btn-danger text-xs gap-2 w-full justify-center">
                <Phone size={13} /> {t('emergency.callNow')}
              </a>
            </div>

            <div className="card p-4">
              <div className="flex items-start gap-2">
                <AlertTriangle size={15} className="text-amber-500 mt-0.5 flex-shrink-0" />
                <p className="text-xs text-slate-600 leading-relaxed">
                  {t('symptom.disclaimer')}
                </p>
              </div>
            </div>

            <div className="card p-5">
              <div className="flex items-center gap-2 mb-4">
                <Lightbulb size={15} className="text-amber-500" />
                <p className="text-sm font-semibold text-slate-900">{t('symptom.tipsTitle')}</p>
              </div>
              <ul className="space-y-2.5">
                {tips.map((tip, i) => (
                  <li key={i} className="flex items-start gap-2.5 text-xs text-slate-600">
                    <div className="w-4 h-4 rounded-full bg-sky-50 border border-sky-100 text-sky-600 flex items-center justify-center flex-shrink-0 text-[10px] font-bold mt-px">{i + 1}</div>
                    {tip}
                  </li>
                ))}
              </ul>
            </div>

            <div className="card p-5">
              <p className="text-sm font-semibold text-slate-900 mb-3">{t('symptom.quickActions')}</p>
              <div className="space-y-2">
                {[
                  { label: 'Health Patterns', href: '/symptom-patterns' },
                  { label: 'Find doctors', href: '/find-doctors' },
                  { label: 'Book appointment', href: '/appointments/new' },
                  { label: 'Medical records', href: '/medical-records' },
                ].map(({ label, href }) => (
                  <Link key={href} href={href} className="flex items-center justify-between py-2 text-xs text-slate-600 hover:text-sky-600 transition-colors group">
                    {label}
                    <ArrowRight size={12} className="text-slate-300 group-hover:text-sky-500 transition-colors" />
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  )
}
